spring:
  h2:
    console:
      enabled: true
      path: /test_db
  datasource:
    driver-class-name: org.h2.Driver # h2 드라이버 설정
    url: jdbc:h2:mem:testdb          # jdbc url 설정 (in-memory db 설정)
    username: sa
    password:
    initialization-mode: always      # datasource 를 타입(h2, mysql, oracle, ...) 에 상관없이 항상 초기화한다.
    platform: h2                     # datasource 타입 플랫폼 정의

    # .sql 파일을 classpath 하위로 두고, 특정 디렉토리 아래에서 실행시킬 수 있다.
    # schema: classpath:db/h2/schema.sql # spring boot startup 시, 특정 경로의 schema.sql 실행
    # data: classpath:db/h2/data.sql # spring boot startup 시, 특정 경로의 data.sql 실행

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none          # ddl 옵션을 무엇으로 할 것인지 (none | create-drop | create | update | validate)
    generate-ddl: true          # true 설정 시, 해당 데이터를 근거로 서버 시작 시점에 DDL 문 생성하여 DB 에 적용 (ddl 생성옵션 링크)
                                # @Entity가 명시된 클래스를 찾아서 ddl을 생성하고 실행한다.
    show-sql: true              # true 설정 시, 콘솔에 JPA 쿼리를 보여준다.
    properties:
      hibernate:
        format_sql: true        # true 설정 시, 콘솔에 표시되는 쿼리를 가독성있게 보여준다.
        use_sql_comments: false # true 설정 시, 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 hint 를 보여준다.

server:
  port: 8070

logging:
  level:
    root: info
  file:
    name: C:/Users/82108/Desktop/log2.log


